/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/csrf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Bootstrap a CSRF context
     * @description Public bootstrap for login/registration and other mutations. Bind token to anonymous/session cookie context; use no-store and explicit allowed origins. Fetch again when the session rotates or the token expires.
     */
    get: operations["getCsrf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a client account
     * @description Creates an unverified client when eligible and schedules verification email. Always return the same generic accepted response for existing/unknown accounts. Role is assigned server-side; no authenticated session until login.
     */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify an email address
     * @description Consumes a single-use verification token. Does not sign the client in automatically.
     */
    post: operations["verifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/resend-verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request another verification email
     * @description Generic response whether the address is unknown, verified, or pending verification; throttle delivery.
     */
    post: operations["resendVerification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a cookie session
     * @description Use a generic invalid-credentials error. Rotate session/CSRF identifiers on success. Unverified accounts may view their profile but booking creation returns 403 until verified.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invalidate the current session
     * @description Requires a valid CSRF context and is repeatable even after the session has expired. Invalidate the server session and clear cookies. A valid authenticated session is not required and 401 is intentionally omitted; obtain a fresh anonymous CSRF context if needed.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request password recovery
     * @description Return a generic accepted response and schedule a reset email only where eligible; never disclose account existence.
     */
    post: operations["forgotPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset a password
     * @description Consumes the reset token, changes the password and revokes existing sessions. Requires a subsequent login.
     */
    post: operations["resetPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the current profile */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update allowed profile fields
     * @description Reject role, email, IDs and other server-owned fields. Null phone removes the optional number.
     */
    patch: operations["updateMe"];
    trace?: never;
  };
  "/v1/topics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List enabled legal consultation services
     * @description The route retains the term topics; each entry represents a firm-approved service. Only enabled services and approved jurisdiction/language/mode/pricing options are public.
     */
    get: operations["listTopics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/topics/{topicId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        topicId: components["parameters"]["TopicId"];
      };
      cookie?: never;
    };
    /** Read an enabled service */
    get: operations["getTopic"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/availability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Find eligible appointment offers
     * @description Offers are not reservations. Server applies roster eligibility, local-office schedules, holidays, buffer times, lead-time rules and DST. Require from < to and enforce a configured maximum search horizon. Offers are bound to the requested language and consultationMode; booking creation must match those selections.
     */
    get: operations["getAvailability"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bookings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the client's own bookings
     * @description Server filters ownership before pagination; no staff-wide listing is implied by this endpoint.
     */
    get: operations["listOwnBookings"];
    put?: never;
    /**
     * Reserve a consultation with a payment hold
     * @description Verified clients only. Atomically recheck slot eligibility and all overlapping lawyer intervals, assign the slot's lawyer, persist a server-priced quote, and create pendingPayment with hold expiry. Do not accept client IDs, prices or status. An offer alone does not secure a slot.
     */
    post: operations["createBooking"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bookings/{bookingId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    /**
     * Read an owned booking and authoritative status
     * @description Ownership enforced for every request. Client reads this state after provider SDK completion instead of assuming payment succeeded.
     */
    get: operations["getOwnBooking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bookings/{bookingId}/intake": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    /**
     * Read the owner's saved intake for resume/prefill
     * @description Account owner only, independently enforced for this sensitive endpoint. Return data:null when no intake has been saved, 404 for a missing/inaccessible booking. Send Cache-Control:no-store and do not log the response.
     */
    get: operations["getOwnIntake"];
    /**
     * Persist minimal confidential consultation intake
     * @description Owner only; permitted before the configured intake cutoff on pendingPayment or confirmed bookings. Replaces the minimal intake payload. Record versioned consent actor/time server-side. No uploads, identity documents or legal advice are accepted by this contract.
     */
    put: operations["putIntake"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bookings/{bookingId}/payment-intents": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create or reuse the booking's PaymentIntent
     * @description Owner and verified email required. Booking must remain pendingPayment with an active hold, current version, completed required intake and any configured screening satisfied. Use the server quote and reuse a compatible provider intent; never charge from browser-supplied amounts. No confirmation until verified provider state is processed.
     */
    post: operations["createPaymentIntent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bookings/{bookingId}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel an owned eligible booking
     * @description Apply the firm's configured cancellation cutoff and refund policy; no policy is established by this draft. Coordinate cancellation with payment/webhook races and release the appointment interval transactionally. Refund status is independent from booking status. Replay the same idempotency key safely.
     */
    post: operations["cancelBooking"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/webhooks/stripe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Durably receive a signed Stripe event
     * @description Provider-to-server endpoint; exempt from cookie/CSRF checks, not from signature verification. Verify Stripe-Signature against the raw request bytes, timestamp tolerance, configured endpoint secret and intended account/environment. Persist event ID uniquely before 200, then process idempotently. Reject invalid signatures with 400; return 503 when durable acceptance fails. Duplicate accepted events return 200. Out-of-order or late success must not bypass booking conflicts/expiry; reconcile or send to an operational exception/refund workflow.
     */
    post: operations["receiveStripeWebhook"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/lawyers/{lawyerId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lawyerId: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    /**
     * Read an approved public lawyer summary
     * @description Resolve lawyerId from an availability offer or booking to display the firm's approved professional name, credentials and languages. Only public approved profiles are returned.
     */
    get: operations["getLawyerSummary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Opaque server-generated identifier. */
    Id: string;
    /**
     * Format: date-time
     * @description Valid RFC 3339 UTC instant ending in Z, with seconds and optional fractional seconds. Offset-form inputs must be converted to UTC by the client; server validates calendar/time values in addition to this pattern.
     */
    UtcInstant: string;
    /**
     * @description Valid IANA timezone validated by the server. Each office/lawyer schedule requires an explicitly configured timezone; there is no location-based production default. The example is synthetic. UTC offsets alone are not accepted.
     * @example Etc/UTC
     */
    TimeZone: string;
    /** @enum {string} */
    Language: "es" | "en";
    /** @enum {string} */
    ConsultationMode: "inPerson" | "video" | "phone";
    /**
     * @description Lowercase three-letter ISO 4217 currency code; the server accepts only firm-configured currencies supported by the payment provider. Syntax alone does not imply a valid or enabled currency. Examples are synthetic, not production defaults. Use the currency-specific minor-unit scale.
     * @example usd
     */
    Currency: string;
    /** @enum {string} */
    Role: "client" | "lawyer" | "admin";
    /** @enum {string} */
    BookingStatus:
      | "pendingPayment"
      | "confirmed"
      | "completed"
      | "noShow"
      | "cancelled"
      | "expired";
    /** @enum {string} */
    PaymentStatus:
      | "unpaid"
      | "requiresAction"
      | "processing"
      | "succeeded"
      | "failed"
      | "cancelled";
    /** @enum {string} */
    RefundStatus: "none" | "pending" | "partial" | "refunded" | "failed";
    FieldError: {
      /** @description camelCase field path. */
      field: string;
      /** @description Stable machine-readable validation code. */
      code: string;
      /** @description Safe display message. */
      message: string;
    };
    Error: {
      error: {
        /** @description Stable machine-readable error code. */
        code: string;
        /** @description Safe display message. */
        message: string;
        /** @description Correlation identifier without confidential matter details. */
        requestId: string;
        fieldErrors?: components["schemas"]["FieldError"][];
      };
    };
    Acknowledgement: {
      /** @enum {boolean} */
      accepted: true;
    };
    Pagination: {
      /** @description Opaque cursor; null when there are no more results. */
      nextCursor: string | null;
    };
    CsrfBootstrap: {
      /** @description CSRF token bound to the anonymous/session context. Hold in memory; do not log. */
      csrfToken: string;
      expiresAt: components["schemas"]["UtcInstant"];
    };
    User: {
      id: components["schemas"]["Id"];
      /** Format: email */
      email: string;
      emailVerified: boolean;
      /** @description Client's given name. */
      givenName: string;
      /** @description Client's family name. */
      familyName: string;
      /** @description E.164 format if supplied; never infer country from office location. */
      phone: string | null;
      preferredLanguage: components["schemas"]["Language"];
      timeZone: components["schemas"]["TimeZone"];
      role: components["schemas"]["Role"];
      createdAt: components["schemas"]["UtcInstant"];
      updatedAt: components["schemas"]["UtcInstant"];
    };
    Session: {
      user: components["schemas"]["User"];
      /** @description New CSRF token after authentication/session rotation. */
      csrfToken: string;
      expiresAt: components["schemas"]["UtcInstant"];
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** @description Password policy is enforced server-side; example minimum is a draft policy. */
      password: string;
      givenName: string;
      familyName: string;
      preferredLanguage: components["schemas"]["Language"];
      timeZone: components["schemas"]["TimeZone"];
      consents: components["schemas"]["ConsentInput"];
    };
    EmailRequest: {
      /** Format: email */
      email: string;
    };
    TokenRequest: {
      /** @description Single-use, expiring verification token; never log. */
      token: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    ResetPasswordRequest: {
      /** @description Single-use, expiring reset token; never log. */
      token: string;
      newPassword: string;
    };
    /** @description Email and role cannot be changed through this endpoint. */
    ProfilePatch: {
      givenName?: string;
      familyName?: string;
      phone?: string | null;
      preferredLanguage?: components["schemas"]["Language"];
      timeZone?: components["schemas"]["TimeZone"];
    };
    Money: {
      /** @description Integer minor units; never floating-point major-unit amounts. */
      amount: number;
      currency: components["schemas"]["Currency"];
    };
    ServicePrice: {
      durationMinutes: number;
      price: components["schemas"]["Money"];
    };
    Topic: {
      id: components["schemas"]["Id"];
      slug: string;
      name: {
        es: string;
        en: string;
      };
      description: {
        es: string;
        en: string;
      };
      jurisdictions: string[];
      durationMinutesOptions: number[];
      languages: components["schemas"]["Language"][];
      consultationModes: components["schemas"]["ConsultationMode"][];
      prices: components["schemas"]["ServicePrice"][];
      active: boolean;
    };
    Slot: {
      id: components["schemas"]["Id"];
      lawyerId: components["schemas"]["Id"];
      topicId: components["schemas"]["Id"];
      durationMinutes: number;
      startAt: components["schemas"]["UtcInstant"];
      endAt: components["schemas"]["UtcInstant"];
      /**
       * Format: date-time
       * @description Expiry of this availability offer, not a reservation. Booking creation rechecks conflicts and eligibility.
       */
      expiresAt: string;
    };
    Availability: {
      slots: components["schemas"]["Slot"][];
      timeZone: components["schemas"]["TimeZone"];
      generatedAt: components["schemas"]["UtcInstant"];
    };
    CreateBookingRequest: {
      slotId: components["schemas"]["Id"];
      topicId: components["schemas"]["Id"];
      durationMinutes: number;
      timeZone: components["schemas"]["TimeZone"];
      language: components["schemas"]["Language"];
      consultationMode: components["schemas"]["ConsultationMode"];
    };
    /** @description Server-issued immutable booking price snapshot in integer minor units; total = subtotal + tax. Tax treatment is configured, not assumed. */
    Quote: {
      subtotal: number;
      tax: number;
      total: number;
      currency: components["schemas"]["Currency"];
      pricingVersion: string;
      expiresAt: components["schemas"]["UtcInstant"];
    };
    /** @description Customer-safe booking view. Does not include legal intake text, private lawyer notes or other customers' information. Status is authoritative server state. */
    Booking: {
      id: components["schemas"]["Id"];
      clientId: components["schemas"]["Id"];
      lawyerId: components["schemas"]["Id"];
      topicId: components["schemas"]["Id"];
      status: components["schemas"]["BookingStatus"];
      paymentStatus: components["schemas"]["PaymentStatus"];
      refundStatus: components["schemas"]["RefundStatus"];
      startAt: components["schemas"]["UtcInstant"];
      endAt: components["schemas"]["UtcInstant"];
      timeZone: components["schemas"]["TimeZone"];
      language: components["schemas"]["Language"];
      consultationMode: components["schemas"]["ConsultationMode"];
      /**
       * Format: date-time
       * @description RFC 3339 UTC instant; serialize with Z.
       */
      holdExpiresAt: string | null;
      quote: components["schemas"]["Quote"];
      /** @enum {string} */
      intakeStatus: "notSubmitted" | "submitted";
      version: number;
      createdAt: components["schemas"]["UtcInstant"];
      updatedAt: components["schemas"]["UtcInstant"];
      /** @description True when late payment, refund failure or another payment/booking mismatch needs staff resolution. Client UI must show a pending-resolution message, not assume an appointment is confirmed. */
      resolutionRequired: boolean;
    };
    /** @description Acceptance of configured notice versions for this workflow; server records actor/time. Marketing consent is not bundled. */
    ConsentInput: {
      privacyNoticeVersion: string;
      termsVersion: string;
    };
    IntakeInput: {
      /** @description Optional brief consultation purpose, not a full case file. Plain text; avoid unnecessary sensitive identifiers. */
      summary?: string;
      preferredLanguage: components["schemas"]["Language"];
      consents: components["schemas"]["ConsentInput"];
    };
    /** @description Acknowledges persistence without echoing confidential intake. */
    IntakeReceipt: {
      bookingId: components["schemas"]["Id"];
      /** @enum {string} */
      status: "submitted";
      submittedAt: components["schemas"]["UtcInstant"];
      bookingVersion: number;
    };
    /** @description No price, currency, customer ID or Stripe secret is accepted from the client. */
    PaymentIntentRequest: {
      bookingVersion: number;
    };
    /** @description Creates or reuses a compatible PaymentIntent for the active booking. SDK completion is not proof that the booking is confirmed. */
    PaymentIntent: {
      bookingId: components["schemas"]["Id"];
      paymentId: components["schemas"]["Id"];
      /** @enum {string} */
      provider: "stripe";
      /** @description Sensitive provider client secret for this owner/booking only. Never log, cache publicly, or persist in URLs. */
      clientSecret: string;
      amount: number;
      currency: components["schemas"]["Currency"];
      paymentStatus: components["schemas"]["PaymentStatus"];
      bookingVersion: number;
    };
    CancelBookingRequest: {
      /** @description Optional plain-text cancellation reason; avoid case details. */
      reason?: string;
    };
    /** @description Provider event envelope only; verify the raw, unmodified body signature and supported Stripe API version before processing. */
    StripeEvent: {
      id: string;
      type: string;
      data: {
        [key: string]: unknown;
      };
    } & {
      [key: string]: unknown;
    };
    WebhookReceipt: {
      /** @enum {boolean} */
      received: true;
    };
    /** @description Owner's current saved intake; null when none exists. Sensitive: Cache-Control no-store. Previously accepted notice versions are metadata, not automatic acceptance of a new notice. */
    SavedIntake: {
      /** @description Optional brief consultation purpose, not a full case file. Plain text; avoid unnecessary sensitive identifiers. */
      summary?: string;
      preferredLanguage: components["schemas"]["Language"];
      consents: components["schemas"]["ConsentInput"];
      bookingId: components["schemas"]["Id"];
      submittedAt: components["schemas"]["UtcInstant"];
      updatedAt: components["schemas"]["UtcInstant"];
      bookingVersion: number;
    } | null;
    /** @description Firm-approved public professional profile only; no private account contacts, schedules or internal case data. The firm verifies credentials and permitted jurisdictions before publication. */
    LawyerSummary: {
      id: components["schemas"]["Id"];
      displayName: string;
      professionalTitle: string;
      credentials: {
        label: string;
        jurisdiction: string;
        publicRegistrationNumber?: string | null;
      }[];
      languages: components["schemas"]["Language"][];
      topicIds: components["schemas"]["Id"][];
      consultationModes: components["schemas"]["ConsultationMode"][];
    };
  };
  responses: {
    /** @description Malformed request, invalid cursor, expired/invalid verification token, or invalid webhook signature. */
    Error400: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Authentication required or credentials/session invalid. */
    Error401: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description CSRF validation failed, email verification required, or action is not permitted. */
    Error403: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource not found or not visible to the authenticated principal; ownership must not be disclosed. */
    Error404: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Slot conflict, stale booking version, invalid state transition, or idempotency key reused with a different body. */
    Error409: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /**
         * @example {
         *       "error": {
         *         "code": "SLOT_UNAVAILABLE",
         *         "message": "The selected appointment is no longer available.",
         *         "requestId": "req_example"
         *       }
         *     }
         */
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Field validation failed, unsupported service/duration/locale/mode combination, or business policy prohibits the action. */
    Error422: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Rate limit exceeded. Retry-After indicates the retry delay. */
    Error429: {
      headers: {
        /** @description Seconds before another attempt when available. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Temporary dependency or service failure. Retry safely using the original idempotency key where required. */
    Error503: {
      headers: {
        /** @description Seconds before another attempt when available. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Accepted. Authentication/recovery flows use a generic response to avoid account enumeration. */
    Acknowledged: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data: components["schemas"]["Acknowledgement"];
        };
      };
    };
    /** @description Session established. Set an HttpOnly, Secure cookie and rotate CSRF/session identifiers; do not return a bearer token. */
    Session: {
      headers: {
        /** @description Session cookie; SameSite policy and allowed credentialed origins must be configured together. */
        "Set-Cookie"?: string;
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data: components["schemas"]["Session"];
        };
      };
    };
    /** @description Successful response. */
    Booking: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data: components["schemas"]["Booking"];
        };
      };
    };
  };
  parameters: {
    BookingId: components["schemas"]["Id"];
    TopicId: components["schemas"]["Id"];
    /** @description Client-generated key scoped to authenticated principal and operation; same key/body replays the original result, conflicting body returns 409. */
    IdempotencyKey: string;
    /** @description Opaque cursor from the preceding list response. */
    Cursor: string;
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getCsrf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["CsrfBootstrap"];
          };
        };
      };
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      202: components["responses"]["Acknowledged"];
      400: components["responses"]["Error400"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequest"];
      };
    };
    responses: {
      200: components["responses"]["Acknowledged"];
      400: components["responses"]["Error400"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  resendVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailRequest"];
      };
    };
    responses: {
      202: components["responses"]["Acknowledged"];
      400: components["responses"]["Error400"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      200: components["responses"]["Session"];
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Acknowledged"];
      403: components["responses"]["Error403"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailRequest"];
      };
    };
    responses: {
      202: components["responses"]["Acknowledged"];
      400: components["responses"]["Error400"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      200: components["responses"]["Acknowledged"];
      400: components["responses"]["Error400"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["User"];
          };
        };
      };
      401: components["responses"]["Error401"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfilePatch"];
      };
    };
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["User"];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  listTopics: {
    parameters: {
      query?: {
        /** @description Opaque cursor from the preceding list response. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Topic"][];
            pagination: components["schemas"]["Pagination"];
          };
        };
      };
      400: components["responses"]["Error400"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  getTopic: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        topicId: components["parameters"]["TopicId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Topic"];
          };
        };
      };
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  getAvailability: {
    parameters: {
      query: {
        /** @description Enabled service. */
        topicId: components["schemas"]["Id"];
        /** @description One duration supported by the selected service. */
        durationMinutes: number;
        /** @description Requested consultation language; eligibility filters the assigned lawyer. */
        language: components["schemas"]["Language"];
        /** @description Requested appointment mode; eligibility is checked for service and lawyer. */
        consultationMode: components["schemas"]["ConsultationMode"];
        /** @description Inclusive search start instant. */
        from: components["schemas"]["UtcInstant"];
        /** @description Exclusive search end instant. */
        to: components["schemas"]["UtcInstant"];
        /** @description Client display timezone; does not change UTC interval meaning. */
        timeZone: components["schemas"]["TimeZone"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "slots": [
           *           {
           *             "id": "slot_example",
           *             "lawyerId": "lawyer_example",
           *             "topicId": "topic_immigration_example",
           *             "durationMinutes": 30,
           *             "startAt": "2030-05-15T17:00:00Z",
           *             "endAt": "2030-05-15T17:30:00Z",
           *             "expiresAt": "2030-05-01T16:02:00Z"
           *           }
           *         ],
           *         "timeZone": "Etc/UTC",
           *         "generatedAt": "2030-05-01T16:00:00Z"
           *       }
           *     }
           */
          "application/json": {
            data: components["schemas"]["Availability"];
          };
        };
      };
      400: components["responses"]["Error400"];
      404: components["responses"]["Error404"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  listOwnBookings: {
    parameters: {
      query?: {
        /** @description Opaque cursor from the preceding list response. */
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        status?: components["schemas"]["BookingStatus"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Booking"][];
            pagination: components["schemas"]["Pagination"];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  createBooking: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated key scoped to authenticated principal and operation; same key/body replays the original result, conflicting body returns 409. */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "slotId": "slot_example",
         *       "topicId": "topic_immigration_example",
         *       "durationMinutes": 30,
         *       "timeZone": "Etc/UTC",
         *       "language": "es",
         *       "consultationMode": "inPerson"
         *     }
         */
        "application/json": components["schemas"]["CreateBookingRequest"];
      };
    };
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": {
           *         "id": "booking_example",
           *         "clientId": "client_example",
           *         "lawyerId": "lawyer_example",
           *         "topicId": "topic_immigration_example",
           *         "status": "pendingPayment",
           *         "paymentStatus": "unpaid",
           *         "refundStatus": "none",
           *         "startAt": "2030-05-15T17:00:00Z",
           *         "endAt": "2030-05-15T17:30:00Z",
           *         "timeZone": "Etc/UTC",
           *         "language": "es",
           *         "consultationMode": "inPerson",
           *         "holdExpiresAt": "2030-05-01T16:10:00Z",
           *         "quote": {
           *           "subtotal": 100000,
           *           "tax": 0,
           *           "total": 100000,
           *           "currency": "usd",
           *           "pricingVersion": "test-price-v1",
           *           "expiresAt": "2030-05-01T16:10:00Z"
           *         },
           *         "intakeStatus": "notSubmitted",
           *         "version": 1,
           *         "createdAt": "2030-05-01T16:00:00Z",
           *         "updatedAt": "2030-05-01T16:00:00Z",
           *         "resolutionRequired": false
           *       }
           *     }
           */
          "application/json": {
            data: components["schemas"]["Booking"];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  getOwnBooking: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Booking"];
      401: components["responses"]["Error401"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  getOwnIntake: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "data": null
           *     }
           */
          "application/json": {
            data: components["schemas"]["SavedIntake"];
          };
        };
      };
      401: components["responses"]["Error401"];
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  putIntake: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "summary": "Consulta inicial sobre un servicio migratorio anunciado por el despacho.",
         *       "preferredLanguage": "es",
         *       "consents": {
         *         "privacyNoticeVersion": "privacy-v1",
         *         "termsVersion": "terms-v1"
         *       }
         *     }
         */
        "application/json": components["schemas"]["IntakeInput"];
      };
    };
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["IntakeReceipt"];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  createPaymentIntent: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated key scoped to authenticated principal and operation; same key/body replays the original result, conflicting body returns 409. */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "bookingVersion": 2
         *     }
         */
        "application/json": components["schemas"]["PaymentIntentRequest"];
      };
    };
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["PaymentIntent"];
          };
        };
      };
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  cancelBooking: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated key scoped to authenticated principal and operation; same key/body replays the original result, conflicting body returns 409. */
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        bookingId: components["parameters"]["BookingId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "reason": "Necesito cambiar mi disponibilidad."
         *     }
         */
        "application/json": components["schemas"]["CancelBookingRequest"];
      };
    };
    responses: {
      200: components["responses"]["Booking"];
      400: components["responses"]["Error400"];
      401: components["responses"]["Error401"];
      403: components["responses"]["Error403"];
      404: components["responses"]["Error404"];
      409: components["responses"]["Error409"];
      422: components["responses"]["Error422"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
  receiveStripeWebhook: {
    parameters: {
      query?: never;
      header: {
        "Stripe-Signature": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StripeEvent"];
      };
    };
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["WebhookReceipt"];
          };
        };
      };
      400: components["responses"]["Error400"];
      503: components["responses"]["Error503"];
    };
  };
  getLawyerSummary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lawyerId: components["schemas"]["Id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["LawyerSummary"];
          };
        };
      };
      404: components["responses"]["Error404"];
      429: components["responses"]["Error429"];
      503: components["responses"]["Error503"];
    };
  };
}
