import type { Booking, Language } from "./api/types";

const en = {
  tagline: "IMMIGRATION & LEGAL GUIDANCE",
  services: "Our services",
  approach: "Our approach",
  how: "How it works",
  login: "Sign in",
  book: "Book a consultation",
  account: "My appointments",
  logout: "Sign out",
  menu: "Open menu",
  close: "Close",
  skip: "Skip to content",
  demo: "Design preview · Sample data only. No real appointments or charges. Do not enter sensitive information.",
  heroEyebrow: "A NEW CHAPTER STARTS WITH CLARITY",
  heroTitle: "Your next step.",
  heroEmphasis: "A clearer path.",
  heroBody:
    "Immigration questions deserve a human conversation. Find your bearings, understand your options, and plan what comes next with legal guidance.",
  heroSecondary: "Explore our services",
  heroNote: "In your language. At your pace.",
  heroArt:
    "An open archway and a winding path, an original illustration for Linde.",
  stripOne: "A conversation that starts with you",
  stripTwo: "Clear steps, from the start",
  stripThree: "Spanish & English",
  servicesEyebrow: "WHAT BRINGS YOU HERE?",
  servicesTitle: "Guidance for the moments that matter.",
  servicesBody:
    "Every story is different. Start with a consultation that makes room for yours.",
  allServices: "Explore all services",
  discover: "Explore consultation",
  from: "From",
  minutes: "min",
  approachEyebrow: "LEGAL GUIDANCE. HUMAN FIRST.",
  approachTitle: "A little clarity can change what comes next.",
  approachBody:
    "A new home. A career opportunity. Being closer to the people you love. Behind every immigration question is a life in motion. Your first consultation is a place to ask, listen, and make sense of the next step.",
  approachLink: "Find your starting point",
  valueOne: "Space to tell your story",
  valueOneBody: "A focused consultation, with time for your questions.",
  valueTwo: "Clarity before commitment",
  valueTwoBody: "Review the service, duration and price before reserving.",
  valueThree: "Your next step, together",
  valueThreeBody:
    "Leave the conversation with a clearer understanding of your options.",
  howEyebrow: "A SIMPLE WAY TO BEGIN",
  howTitle: "From a question to a conversation.",
  stepOne: "Choose your consultation",
  stepOneBody: "Find the service that best fits what you want to discuss.",
  stepTwo: "Make time for yourself",
  stepTwoBody: "Choose an available appointment in your timezone.",
  stepThree: "Take the next step",
  stepThreeBody: "Confirm your reservation and prepare for your consultation.",
  ctaTitle: "You do not need all the answers to begin.",
  ctaBody: "Just a question, and a little time to talk.",
  footerBody: "Legal guidance for what comes next.",
  footerNote:
    "Consultation booking does not itself establish legal representation. Service availability depends on the firm’s authorized jurisdictions.",
  contact: "Contact",
  privacy: "Privacy",
  terms: "Terms",
  cancellation: "Cancellation policy",
  rights: "Linde. All rights reserved.",
  loading: "Loading…",
  retry: "Try again",
  error: "We could not complete that request.",
  unavailable:
    "Online appointments are not available yet. Please check back soon.",
  network: "We could not connect. Check your connection and try again.",
  unauthorized: "Please sign in again to continue.",
  forbidden:
    "This action is not available for your account. Check whether your email needs verification.",
  conflict:
    "This appointment changed or the time is no longer available. Refresh and choose another time.",
  invalid: "Please check the information and try again.",
  notFound: "We could not find that page.",
  notFoundBody: "It may have moved, or the link may no longer be available.",
  home: "Back to home",
  emptyServices:
    "Consultation services will appear here when online booking opens.",
  catalogueTitle: "Start with what matters to you.",
  catalogueBody: "Explore consultation options, then choose a time to talk.",
  serviceIntro: "YOUR CONSULTATION",
  serviceDetails: "A focused conversation about your next step.",
  duration: "Duration",
  language: "Consultation language",
  mode: "Consultation format",
  jurisdiction: "Available jurisdictions",
  servicePreparation: "Bring your questions",
  preparationBody:
    "Think about what you would like to understand. You can add a short, optional note when booking. Do not upload identity documents or share detailed case information here.",
  video: "Video consultation",
  phone: "Phone consultation",
  inPerson: "In person",
  bookingTitle: "Make room for your next step.",
  bookingBody: "Choose a consultation and a time that works for you.",
  chooseService: "Choose a consultation",
  chooseTime: "Choose a time",
  review: "Review & reserve",
  selectService: "Consultation",
  timezone: "Your timezone",
  timezoneHelp: "All times below are shown in your selected timezone.",
  date: "Day",
  time: "Available times",
  noSlots:
    "No times are available for this selection. Try another week or format.",
  nextWeek: "Next week",
  previousWeek: "Previous week",
  selected: "Your selection",
  continue: "Continue",
  back: "Back",
  reserve: "Reserve this time",
  reservationNote:
    "Your appointment is confirmed only after the required payment is verified.",
  note: "Anything you would like us to know?",
  optional: "Optional",
  noteHelp:
    "A brief purpose is enough. Please leave out identity numbers and sensitive documents.",
  accept: "I have read the privacy notice and terms.",
  policyPending:
    "Booking will open once the firm’s terms and privacy notice are published.",
  previewPolicy: "Preview notices are examples, not published firm policies.",
  lawyer: "Consultation professional",
  schedule: "Appointment",
  price: "Consultation fee",
  total: "Total",
  tax: "Tax",
  loginTitle: "Welcome back.",
  loginBody: "Your next conversation is waiting.",
  email: "Email address",
  password: "Password",
  givenName: "First name",
  familyName: "Last name",
  forgot: "Forgot your password?",
  noAccount: "New to Linde?",
  register: "Create an account",
  registerTitle: "A clear place to begin.",
  registerBody: "Create your account to book and manage your consultations.",
  haveAccount: "Already have an account?",
  passwordHint: "Use at least 12 characters.",
  demoLogin: "Explore the sample account",
  signedIn: "You are signed in.",
  registerDone:
    "If this address is eligible, we will send instructions to verify your email. Check your inbox before signing in.",
  forgotTitle: "Let’s get you back in.",
  forgotBody:
    "We will send a reset link if there is an account for this address.",
  sendLink: "Send reset link",
  emailSent: "If an account exists, instructions will arrive in your inbox.",
  resetTitle: "Choose a new password.",
  newPassword: "New password",
  reset: "Save new password",
  resetDone: "Your password has been updated. You can sign in now.",
  verifyTitle: "Verify your email.",
  verifyBody: "Confirm your email address to start booking consultations.",
  verify: "Verify email",
  verified: "Your email is verified. You can sign in now.",
  missingToken: "Open the complete link from your email to continue.",
  resend: "Resend verification email",
  dashboardEyebrow: "YOUR SPACE",
  dashboardTitle: "A little more clarity, all in one place.",
  dashboardBody: "Your consultations and next steps.",
  upcoming: "Upcoming",
  all: "All appointments",
  past: "Past & cancelled",
  emptyAppointments: "Your next chapter starts with a conversation.",
  emptyAppointmentsBody:
    "You have no appointments here yet. Find a consultation when you are ready.",
  details: "View appointment",
  loadMore: "Load more",
  appointmentTitle: "Your consultation.",
  reference: "Booking reference",
  payment: "Payment",
  intakeTitle: "Your consultation note",
  saveNote: "Save note",
  saved: "Your note has been saved.",
  noteSaveFailed:
    "Your reservation was saved, but your note could not be saved. You can add it again below.",
  cancel: "Cancel appointment",
  cancelTitle: "Cancel this appointment?",
  cancelBody:
    "This releases the reserved time. Any refund is handled separately under the firm’s cancellation policy.",
  keepBooking: "Keep appointment",
  confirmCancel: "Yes, cancel appointment",
  refundPending:
    "Your refund is pending review. Cancelling does not mean a refund has already arrived.",
  resolution:
    "This payment needs review. Your appointment is not confirmed unless its status says confirmed. The firm will resolve the payment separately.",
  expired: "This reservation has expired. Choose a new time to continue.",
  hold: "Time remaining to complete payment",
  payTitle: "One more step to your consultation.",
  payBody: "Review your reservation and complete your payment securely.",
  pay: "Continue to payment",
  payNow: "Pay consultation fee",
  card: "Card details",
  securePayment: "Card details are handled by Stripe.",
  paymentUnavailable:
    "Online payment is not available yet. Your reservation has not been confirmed.",
  demoPayment: "Simulate successful payment",
  demoPaymentNote:
    "Preview only. No card information is collected and no charge is made.",
  processing:
    "We are checking your payment. This page will update when your appointment is confirmed.",
  confirmedTitle: "Your time is reserved.",
  confirmedBody:
    "Your consultation is confirmed. You can return here for your appointment details.",
  checkStatus: "Check appointment status",
  receipt: "Payment received",
  support: "Need a hand?",
  supportBody:
    "Sign in to review your consultation details. Contact information will be published here once confirmed by the firm.",
  contactTitle: "Let’s find your next step.",
  legalPending: "The firm’s approved policy has not been published yet.",
  publishedPolicy: "Read the policy published by the firm before continuing.",
  readPolicy: "Read the published policy",
  legalBody:
    "This page is reserved for the firm’s reviewed policy. No operational terms, refunds or privacy commitments are implied by this preview.",
  demoLegal:
    "Preview notice: this local demonstration uses synthetic account data and temporary browser-tab storage. Do not enter real personal, immigration or payment information. This is not the firm’s production privacy notice or terms.",
  teamTitle: "A considered space for your work.",
  teamBody:
    "The staff workspace will connect to the firm’s separately defined operations API. No client records or administrative actions are exposed here.",
  profile: "Profile",
  pageAnnouncement: "Page loaded",
} as const;
const es: Record<keyof typeof en, string> = {
  tagline: "INMIGRACIÓN Y ORIENTACIÓN LEGAL",
  services: "Especialidades",
  approach: "Nuestro enfoque",
  how: "Cómo funciona",
  login: "Ingresar",
  book: "Agendar una consulta",
  account: "Mis consultas",
  logout: "Cerrar sesión",
  menu: "Abrir menú",
  close: "Cerrar",
  skip: "Ir al contenido",
  demo: "Vista previa · Datos de ejemplo. Sin citas ni cobros reales. No ingreses información sensible.",
  heroEyebrow: "UN NUEVO CAPÍTULO COMIENZA CON CLARIDAD",
  heroTitle: "Tu siguiente paso.",
  heroEmphasis: "Un camino más claro.",
  heroBody:
    "Tus preguntas sobre inmigración merecen una conversación humana. Encuentra orientación, conoce tus opciones y planea lo que viene con acompañamiento legal.",
  heroSecondary: "Conoce nuestras especialidades",
  heroNote: "En tu idioma. A tu ritmo.",
  heroArt:
    "Un arco abierto y un camino sinuoso, una ilustración original de Linde.",
  stripOne: "Una conversación que empieza contigo",
  stripTwo: "Pasos claros, desde el inicio",
  stripThree: "Español e inglés",
  servicesEyebrow: "¿QUÉ TE TRAE POR AQUÍ?",
  servicesTitle: "Orientación para los momentos que importan.",
  servicesBody:
    "Cada historia es distinta. Comienza con una consulta que le dé espacio a la tuya.",
  allServices: "Ver todas las especialidades",
  discover: "Conocer la consulta",
  from: "Desde",
  minutes: "min",
  approachEyebrow: "ORIENTACIÓN LEGAL. PRIMERO, LAS PERSONAS.",
  approachTitle: "Un poco de claridad puede cambiar lo que viene.",
  approachBody:
    "Un nuevo hogar. Una oportunidad profesional. Estar más cerca de quienes quieres. Detrás de cada pregunta migratoria hay una vida en movimiento. Tu primera consulta es un espacio para preguntar, escuchar y entender el siguiente paso.",
  approachLink: "Encuentra tu punto de partida",
  valueOne: "Espacio para tu historia",
  valueOneBody: "Una consulta enfocada, con tiempo para tus preguntas.",
  valueTwo: "Claridad antes de decidir",
  valueTwoBody:
    "Conoce el servicio, la duración y el precio antes de reservar.",
  valueThree: "Tu siguiente paso, en compañía",
  valueThreeBody: "Una conversación para entender mejor tus opciones.",
  howEyebrow: "UNA FORMA SENCILLA DE COMENZAR",
  howTitle: "De una pregunta a una conversación.",
  stepOne: "Elige tu consulta",
  stepOneBody:
    "Encuentra el servicio que mejor se ajuste a lo que quieres conversar.",
  stepTwo: "Haz un espacio para ti",
  stepTwoBody: "Elige un horario disponible en tu zona horaria.",
  stepThree: "Da el siguiente paso",
  stepThreeBody: "Confirma tu reservación y prepárate para tu consulta.",
  ctaTitle: "No necesitas todas las respuestas para empezar.",
  ctaBody: "Solo una pregunta y un poco de tiempo para conversar.",
  footerBody: "Orientación legal para lo que viene.",
  footerNote:
    "Agendar una consulta no establece por sí mismo una relación de representación legal. Los servicios dependen de las jurisdicciones autorizadas del despacho.",
  contact: "Contacto",
  privacy: "Privacidad",
  terms: "Términos",
  cancellation: "Política de cancelación",
  rights: "Linde. Todos los derechos reservados.",
  loading: "Cargando…",
  retry: "Volver a intentar",
  error: "No pudimos completar la solicitud.",
  unavailable: "Las citas en línea aún no están disponibles. Vuelve pronto.",
  network: "No pudimos conectarnos. Revisa tu conexión e intenta de nuevo.",
  unauthorized: "Ingresa de nuevo para continuar.",
  forbidden:
    "Esta acción no está disponible para tu cuenta. Revisa si necesitas verificar tu correo.",
  conflict:
    "La consulta cambió o el horario ya no está disponible. Actualiza y elige otro horario.",
  invalid: "Revisa la información e intenta de nuevo.",
  notFound: "No encontramos esta página.",
  notFoundBody:
    "Es posible que se haya movido o que el enlace ya no esté disponible.",
  home: "Volver al inicio",
  emptyServices:
    "Las consultas aparecerán aquí cuando se habiliten las citas en línea.",
  catalogueTitle: "Empieza por lo que te importa.",
  catalogueBody: "Explora las opciones y encuentra un momento para conversar.",
  serviceIntro: "TU CONSULTA",
  serviceDetails: "Una conversación enfocada en tu siguiente paso.",
  duration: "Duración",
  language: "Idioma de la consulta",
  mode: "Modalidad de consulta",
  jurisdiction: "Jurisdicciones disponibles",
  servicePreparation: "Trae tus preguntas",
  preparationBody:
    "Piensa en lo que te gustaría entender. Puedes añadir una nota breve y opcional al reservar. No compartas documentos de identidad ni detalles sensibles de tu caso aquí.",
  video: "Videollamada",
  phone: "Llamada telefónica",
  inPerson: "Presencial",
  bookingTitle: "Haz espacio para tu siguiente paso.",
  bookingBody: "Elige una consulta y un horario que funcione para ti.",
  chooseService: "Elige tu consulta",
  chooseTime: "Elige un horario",
  review: "Revisa y reserva",
  selectService: "Consulta",
  timezone: "Tu zona horaria",
  timezoneHelp: "Todos los horarios se muestran en la zona que selecciones.",
  date: "Día",
  time: "Horarios disponibles",
  noSlots:
    "No hay horarios para esta selección. Prueba otra semana o modalidad.",
  nextWeek: "Siguiente semana",
  previousWeek: "Semana anterior",
  selected: "Tu selección",
  continue: "Continuar",
  back: "Regresar",
  reserve: "Reservar este horario",
  reservationNote:
    "Tu consulta se confirma únicamente cuando se verifica el pago requerido.",
  note: "¿Algo que te gustaría compartir?",
  optional: "Opcional",
  noteHelp:
    "Basta con un motivo breve. Evita números de identificación y documentos sensibles.",
  accept: "He leído el aviso de privacidad y los términos.",
  policyPending:
    "Las reservas se habilitarán cuando se publiquen los términos y el aviso de privacidad del despacho.",
  previewPolicy:
    "Los avisos de esta vista previa son ejemplos, no políticas publicadas del despacho.",
  lawyer: "Profesional de la consulta",
  schedule: "Cita",
  price: "Precio de la consulta",
  total: "Total",
  tax: "Impuesto",
  loginTitle: "Qué gusto tenerte de vuelta.",
  loginBody: "Tu siguiente conversación te espera.",
  email: "Correo electrónico",
  password: "Contraseña",
  givenName: "Nombre",
  familyName: "Apellido",
  forgot: "¿Olvidaste tu contraseña?",
  noAccount: "¿Primera vez en Linde?",
  register: "Crear una cuenta",
  registerTitle: "Un lugar claro para comenzar.",
  registerBody: "Crea tu cuenta para agendar y gestionar tus consultas.",
  haveAccount: "¿Ya tienes cuenta?",
  passwordHint: "Usa al menos 12 caracteres.",
  demoLogin: "Explorar la cuenta de ejemplo",
  signedIn: "Ya iniciaste sesión.",
  registerDone:
    "Si el correo es elegible, enviaremos instrucciones para verificarlo. Revisa tu bandeja antes de ingresar.",
  forgotTitle: "Volvamos a tu cuenta.",
  forgotBody: "Enviaremos un enlace si existe una cuenta con este correo.",
  sendLink: "Enviar enlace",
  emailSent: "Si existe una cuenta, las instrucciones llegarán a tu correo.",
  resetTitle: "Elige una nueva contraseña.",
  newPassword: "Nueva contraseña",
  reset: "Guardar contraseña",
  resetDone: "Actualizamos tu contraseña. Ya puedes ingresar.",
  verifyTitle: "Verifica tu correo.",
  verifyBody:
    "Confirma tu correo electrónico para empezar a reservar consultas.",
  verify: "Verificar correo",
  verified: "Tu correo está verificado. Ya puedes ingresar.",
  missingToken: "Abre el enlace completo de tu correo para continuar.",
  resend: "Reenviar correo de verificación",
  dashboardEyebrow: "TU ESPACIO",
  dashboardTitle: "Un poco más de claridad, en un solo lugar.",
  dashboardBody: "Tus consultas y siguientes pasos.",
  upcoming: "Próximas",
  all: "Todas las consultas",
  past: "Pasadas y canceladas",
  emptyAppointments: "Tu siguiente capítulo empieza con una conversación.",
  emptyAppointmentsBody:
    "Todavía no tienes consultas aquí. Encuentra una cuando estés listo.",
  details: "Ver consulta",
  loadMore: "Cargar más",
  appointmentTitle: "Tu consulta.",
  reference: "Referencia de reserva",
  payment: "Pago",
  intakeTitle: "Tu nota para la consulta",
  saveNote: "Guardar nota",
  saved: "Guardamos tu nota.",
  noteSaveFailed:
    "Guardamos tu reservación, pero no pudimos guardar tu nota. Puedes añadirla de nuevo abajo.",
  cancel: "Cancelar consulta",
  cancelTitle: "¿Cancelar esta consulta?",
  cancelBody:
    "Se liberará el horario reservado. Cualquier reembolso se gestiona por separado según la política del despacho.",
  keepBooking: "Conservar consulta",
  confirmCancel: "Sí, cancelar consulta",
  refundPending:
    "Tu reembolso está pendiente de revisión. Cancelar no significa que el dinero ya haya llegado.",
  resolution:
    "Este pago necesita revisión. Tu consulta solo está confirmada si su estado lo indica. El despacho resolverá el pago por separado.",
  expired: "Esta reservación venció. Elige otro horario para continuar.",
  hold: "Tiempo restante para completar el pago",
  payTitle: "Un paso más para tu consulta.",
  payBody: "Revisa tu reservación y completa tu pago de forma segura.",
  pay: "Continuar al pago",
  payNow: "Pagar consulta",
  card: "Datos de la tarjeta",
  securePayment: "Stripe gestiona los datos de tu tarjeta.",
  paymentUnavailable:
    "El pago en línea aún no está disponible. Tu reservación no está confirmada.",
  demoPayment: "Simular pago exitoso",
  demoPaymentNote:
    "Solo vista previa. No se recopilan datos de tarjeta ni se realiza ningún cobro.",
  processing:
    "Estamos verificando tu pago. La página se actualizará cuando se confirme tu consulta.",
  confirmedTitle: "Tu tiempo está reservado.",
  confirmedBody:
    "Tu consulta está confirmada. Puedes volver aquí para revisar sus detalles.",
  checkStatus: "Consultar estado de la cita",
  receipt: "Pago recibido",
  support: "¿Necesitas ayuda?",
  supportBody:
    "Ingresa para revisar los detalles de tu consulta. Publicaremos los datos de contacto cuando el despacho los confirme.",
  contactTitle: "Encontremos tu siguiente paso.",
  legalPending: "La política aprobada del despacho aún no se ha publicado.",
  publishedPolicy:
    "Lee la política publicada por el despacho antes de continuar.",
  readPolicy: "Leer la política publicada",
  legalBody:
    "Este espacio está reservado para la política revisada por el despacho. Esta vista previa no establece condiciones operativas, reembolsos ni compromisos de privacidad.",
  demoLegal:
    "Aviso de vista previa: esta demostración local utiliza datos de cuenta sintéticos y almacenamiento temporal en la pestaña del navegador. No ingreses información personal, migratoria ni de pago real. No es el aviso de privacidad ni los términos de producción del despacho.",
  teamTitle: "Un espacio pensado para tu trabajo.",
  teamBody:
    "El espacio del equipo se conectará a la API de operaciones que el despacho defina por separado. Aquí no se exponen datos de clientes ni acciones administrativas.",
  profile: "Perfil",
  pageAnnouncement: "Página cargada",
};
export type CopyKey = keyof typeof en;
export const copy = { es, en };
export const statusLabels: Record<
  Language,
  Record<Booking["status"], string>
> = {
  en: {
    pendingPayment: "Awaiting payment",
    confirmed: "Confirmed",
    completed: "Completed",
    noShow: "Not attended",
    cancelled: "Cancelled",
    expired: "Expired",
  },
  es: {
    pendingPayment: "Pendiente de pago",
    confirmed: "Confirmada",
    completed: "Completada",
    noShow: "Sin asistencia",
    cancelled: "Cancelada",
    expired: "Vencida",
  },
};
